# PostgreSQL Veri Tabani Baglanti Bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/kap_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Ayarlari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# KAP API Ayarlari
kap.datafeed.base-url=${KAP_DATAFEED_BASE_URL}
kap.datafeed.him-base-url=${KAP_HIM_BASE_URL}

# JWT Ayarlari
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=18000000